name = "juggernaut-debug"
compatibility_date = "2023-11-21"

[build]
command = "bash build.sh"
cwd = "."

[build.environment]
NODE_VERSION = "18"

[pages_build_output]
directory = "dist"

[env.production]
vars = { BUILD_ENV = "production" }
